image: ruby:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - gem install bundler
          - bundle install
          - bundle exec jekyll build
  branches:
    master:
      - step:
          script:
            - gem install bundler
            - bundle install
            - bundle exec jekyll build
            - git push https://$githubtoken@github.com/modelabcl/modelabcl.github.io.git master 